name: build-and-release

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    uses: ./.github/workflows/build-library.yml
    with:
      library-name: ttutil
      platform: linux
      build-command: pixi run build-linux
      build-dir: builddir
      runner: ubuntu-latest
    permissions:
      contents: write

  build-windows:
    uses: ./.github/workflows/build-library.yml
    with:
      library-name: ttutil
      platform: windows
      build-command: pixi run build-windows-native
      build-dir: builddir_windows_native
      runner: windows-latest

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-libs
          path: dist/linux

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-libs
          path: dist/windows

      - name: Create git tag from pixi.toml version
        id: tag_version
        run: |
          VERSION=$(grep '^version' pixi.toml | head -n1 | awk -F\" '{print $2}')
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v$VERSION"
          git push origin "v$VERSION"
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/linux/libttutil${{ needs.build-linux.outputs.version }}-linux.a
            dist/windows/libttutil${{ needs.build-linux.outputs.version }}-windows.a
          tag_name: ${{ steps.tag_version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
